[book]
authors      = ["Marc Webrainer"]
language     = "en"
multilingual = false
src          = "src"
title        = "Documentation"

[build]
build-dir      = "dist"
create-missing = false

[output.html]
default-theme       = "navy"
git-repository-url  = "https://github.com/fishfolk/jumpy"
git-repository-icon = "fa-github"
